"""add indexing

Revision ID: 4d71d7be36fc
Revises: bac0544020f8
Create Date: 2026-02-23 12:00:14.887216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d71d7be36fc'
down_revision = 'bac0544020f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index('idx_address_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index('idx_cartitem_cart_id', ['cart_id'], unique=False)
        batch_op.create_index('idx_cartitem_product_id', ['product_id'], unique=False)
        batch_op.create_unique_constraint('unique_cart_product', ['cart_id', 'product_id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('idx_orderitem_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_orderitem_product_id', ['product_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_order_address_id', ['address_id'], unique=False)
        batch_op.create_index('idx_order_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_order_payment_status', ['payment_status'], unique=False)
        batch_op.create_index('idx_order_status', ['order_status'], unique=False)
        batch_op.create_index('idx_order_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('product_details', schema=None) as batch_op:
        batch_op.create_index('idx_product_name', ['name'], unique=False)
        batch_op.create_index('idx_product_stock', ['stock'], unique=False)
        batch_op.create_index('idx_product_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('idx_role_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_user_is_active', ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_is_active')
        batch_op.drop_index('idx_user_created_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('idx_role_is_active')

    with op.batch_alter_table('product_details', schema=None) as batch_op:
        batch_op.drop_index('idx_product_user_id')
        batch_op.drop_index('idx_product_stock')
        batch_op.drop_index('idx_product_name')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_order_user_id')
        batch_op.drop_index('idx_order_status')
        batch_op.drop_index('idx_order_payment_status')
        batch_op.drop_index('idx_order_created_at')
        batch_op.drop_index('idx_order_address_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('idx_orderitem_product_id')
        batch_op.drop_index('idx_orderitem_order_id')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('unique_cart_product', type_='unique')
        batch_op.drop_index('idx_cartitem_product_id')
        batch_op.drop_index('idx_cartitem_cart_id')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index('idx_address_user_id')

    # ### end Alembic commands ###
