"""add address id and delivery address column to order table

Revision ID: 654d69b659cf
Revises: e244e01ce03f
Create Date: 2026-01-30 12:16:30.990625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654d69b659cf'
down_revision = 'e244e01ce03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=False))
        batch_op.create_foreign_key(None, 'address', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###
