"""add Enum class to order_status and payment_status

Revision ID: 7ae99f606b22
Revises: 654d69b659cf
Create Date: 2026-02-03 15:41:52.845641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ae99f606b22'
down_revision = '654d69b659cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'INITIATED', 'SUCCESS', 'FAILED', 'REFUND_PENDING', 'REFUNDED', name='paymentstatus'),
               nullable=False)
        batch_op.alter_column('order_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PLACED', 'READY_TO_SHIP', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED', 'REFUNDED', name='orderstatus'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_status',
               existing_type=sa.Enum('PENDING', 'PLACED', 'READY_TO_SHIP', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED', 'REFUNDED', name='orderstatus'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('PENDING', 'INITIATED', 'SUCCESS', 'FAILED', 'REFUND_PENDING', 'REFUNDED', name='paymentstatus'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
