"""create product table

Revision ID: a910b831398a
Revises: 
Create Date: 2026-01-07 18:14:57.143201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a910b831398a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    #### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product_Details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_number', sa.String(length=100), nullable=False),
    sa.Column('specification', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_number'),
    sa.UniqueConstraint('name')
    )
    ### # end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Product_Details')
    # ### end Alembic commands ###
