"""add a new column user_id to the table

Revision ID: cf9e9a8184bf
Revises: 76db806be9ca
Create Date: 2026-01-15 15:56:25.520929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf9e9a8184bf'
down_revision = '76db806be9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'product_details',
        sa.Column('user_id', sa.Integer(), nullable=False)
    )

    # op.create_foreign_key(
    #     'fk_product_user',
    #     'product_details',
    #     'user',
    #     ['user_id'],
    #     ['id']
    # )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('fk_product_user', 'product_details', type_='foreignkey')
    op.drop_column('product_details', 'user_id')
