"""baseline

Revision ID: fa74e53e882a
Revises: 7ae99f606b22
Create Date: 2026-02-09 16:49:15.491807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa74e53e882a'
down_revision = '7ae99f606b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:

        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Populate existing rows
    op.execute("UPDATE user SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE user SET updated_at = NOW() WHERE updated_at IS NULL")

    # Now enforce NOT NULL
    with op.batch_alter_table('user') as batch_op:

        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(),
            nullable=False
        )

        batch_op.alter_column(
            'updated_at',
            existing_type=sa.DateTime(),
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_superadmin')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
